jhekasoft_testform:
    resource: "@JhekasoftTestformBundle/Resources/config/routing.yml"
    prefix:   /

# redirecting the root
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /testform
        permanent: true