_registration_welcome:
    path:     /registration/welcome
    defaults: { _controller: JhekasoftRegistrationBundle:Default:index }

_registration_login:
    path:     /registration/login
    defaults: { _controller: JhekasoftRegistrationBundle:Default:login }

_registration_logout:
    path:     /registration/logout
    defaults: { _controller: JhekasoftRegistrationBundle:Default:logout }

_registration_security_check:
    path:     /registration/security-check
    defaults: { _controller: JhekasoftRegistrationBundle:Default:securityCheck }

_registration_register:
    path:     /registration/register
    defaults: { _controller: JhekasoftRegistrationBundle:Default:register }

_registration_create:
    path:     /registration/create
    defaults: { _controller: JhekasoftRegistrationBundle:Default:create }

_registration_completed:
    path:     /registration/completed/{email}
    defaults: { _controller: JhekasoftRegistrationBundle:Default:completed }

_registration_verificate:
    path:     /registration/verificate/{hash}
    defaults: { _controller: JhekasoftRegistrationBundle:Default:verificate }